# Generated by Django 5.1.1 on 2024-11-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_company_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='documentoIdentidad',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
