# Generated by Django 5.1.1 on 2024-11-07 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_advertiserrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertiserrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('accepted', 'Aceptada'), ('rejected', 'Rechazada')], default='pending', max_length=10),
        ),
    ]
