# Generated by Django 5.1.1 on 2024-11-07 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_advertiserrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertiserrequest',
            name='description',
            field=models.TextField(default='descripción de pruba'),
            preserve_default=False,
        ),
    ]
