# Generated by Django 5.1.1 on 2024-09-21 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(default='company/images/default.jpg', upload_to='company/images/'),
        ),
    ]
