# Generated by Django 5.1.1 on 2024-09-22 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_company_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
    ]
