# Generated by Django 5.1.1 on 2024-09-22 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='phone',
        ),
    ]
